name: jb-docker-compose

services:
  database:
    image: mysql:8.0
    container_name: jb-database
    environment:
      MYSQL_ROOT_PASSWORD: jb
      MYSQL_DATABASE: jb
      MYSQL_USER: jb
      MYSQL_PASSWORD: jb
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - jb-db:/var/lib/mysql

  db-admin:
    container_name: jb-db-admin
    image: phpmyadmin/phpmyadmin
    ports:
      - "5000:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: jb
    restart: always

volumes:
  jb-db: